#!/bin/bash

rm out_file_map out_file_map_std out_file_set_std out_file_set out_file_stack out_file_vector out_file_vector_std out_file_stack_std
rm timing_file_map timing_file_map_std timing_file_set timing_file_set_std timing_file_stack timing_file_stack_std timing_file_vector timing_file_vector_std